module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "Dinu Production",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94760177471",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "true",
  "ANTI_BOT": "true",
  "ANTI_CALL": "false",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "true",
  "ANTI_STICKER": "true",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94760177471",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "true",
  "OWNER_NAME": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "94742274855",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
  "AI_MODE": false,
};
